// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
/*
 * File Name: main.go
 * Author: Sphantix
 * Mail: sphantix@gmail.cn
 * Created Time: 一 15  7 2019 10:57:01 下午 CST
 */

package main

//int sum(int a, int b);
import _ "unsafe"

//export sum
func sum(a, b  /*line :14:15*/_Ctype_int /*line :14:20*/)  /*line :14:22*/_Ctype_int /*line :14:27*/ {
	return a + b
}

func main() {}
