// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
/*
 * File Name: main.go
 * Author: Sphantix
 * Mail: sphantix@gmail.cn
 * Created Time: Sun 14 Jul 2019 10:57:24 PM CST
 */

package main

//int sum(int a, int b) {return a+b;}
import _ "unsafe"

func main() {
	println(( /*line :14:10*/_Cfunc_sum /*line :14:14*/)(1, 1))
}
